USE [QLA-S1]
CREATE SCHEMA HR
CREATE TABLE HR.EMPLOYEE(
	SSN INT PRIMARY KEY,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	BIRTHDATE DATE,
	GENDER CHAR CHECK (GENDER IN ('M' ,'F')),
	SUPERID INT,
	DEPTNUM INT,
	FOREIGN KEY (SUPERID) REFERENCES HR.EMPLOYEE(SSN),
	FOREIGN KEY (DEPTNUM) REFERENCES HR.DEPARTMENT(DNUM),

);

CREATE SCHEMA HR
CREATE TABLE HR.DEPARTMENT(
	DNUM INT PRIMARY KEY,
	DNAME VARCHAR(50),
	CITY VARCHAR(50),
	MANAGESSN INT,
);

CREATE SCHEMA HR
CREATE TABLE HR.PROJECT(
	PNUM INT PRIMARY KEY,
	PNAME VARCHAR(50),
	CITY VARCHAR(50),
	EMPSSN INT,
	DNUM INT,
);

INSERT INTO HR.EMPLOYEE (SSN, Fname, Lname, BirthDate, Gender, SUPERID, DEPTNUM) VALUES
(1001, 'Ahmed', 'FATHY', '1990-05-12', 'M', NULL, 1), 
(1002, 'Sara', 'Ali', '1995-03-20', 'F', 1001, 1), 
(1003, 'Omar', 'Nabil', '1988-11-02', 'M', NULL, 2), 
(1004, 'Mona', 'Ibrahim', '1993-07-08', 'F', 1003, 2),  
(1005, 'Youssef', 'AHMED', '1997-09-15', 'M', 1003, 2);


INSERT INTO HR.DEPARTMENT (Dnum, Dname, CITY) VALUES
(1, 'HR', 'Cairo'),
(2, 'IT', 'BANHA'),
(3, 'Finance', 'Giza');

UPDATE HR.EMPLOYEE
SET DEPTNUM = 3
WHERE SSN = 1002;

SELECT *
FROM HR.EMPLOYEE
WHERE DEPTNUM = 2;

